language: ruby

sudo: false
cache: bundler

rvm:
  - 2.5.1
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

before_script:
  - psql -c 'drop database if exists shop_example_test' -U postgres
  - psql -c 'create database shop_example_test' -U postgres
  - gem install bundler --no-document

script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake spec
